# Generated by Django 4.2.9 on 2024-02-10 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("first_name", models.CharField(max_length=100, verbose_name="First Name")),
                ("last_name", models.CharField(max_length=100, verbose_name="Last Name")),
                ("email", models.EmailField(max_length=100, unique=True, verbose_name="Email")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Phone Number"
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        choices=[("home", "Home"), ("office", "Office"), ("mobile", "Mobile"), ("other", "Other")],
                        default="mobile",
                        max_length=10,
                        verbose_name="Phone Type",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("cohabit", "Co-Habitating"),
                            ("other", "Other"),
                        ],
                        default="single",
                        max_length=50,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-Binary"),
                            ("refuse_id", "Refuse to Identify"),
                            ("other", "Other"),
                        ],
                        verbose_name="Gender",
                    ),
                ),
                ("birthdate", models.DateField(blank=True, null=True, verbose_name="Birthdate")),
                (
                    "pronoun",
                    models.CharField(
                        blank=True,
                        choices=[("he", "He/Him"), ("she", "She/Her"), ("they", "They/Them"), ("other", "Other")],
                        verbose_name="Pronoun",
                    ),
                ),
                ("can_text", models.BooleanField(default=True, verbose_name="Can Text")),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("client", "Client"), ("vendor", "Vendor"), ("other", "Other")],
                        default="client",
                        max_length=10,
                        verbose_name="Contact Type",
                    ),
                ),
                ("can_email", models.BooleanField(default=True, verbose_name="Can Email")),
                ("can_snail_mail", models.BooleanField(default=False, verbose_name="Can Snail Mail")),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="agents.agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Lead User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
