# Generated by Django 4.2.9 on 2024-02-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="contact_type",
            field=models.CharField(
                choices=[("lead", "Lead"), ("client", "Client"), ("vendor", "Vendor"), ("other", "Other")],
                default="lead",
                max_length=10,
                verbose_name="Contact Type",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("cohabit", "Co-Habitating"),
                    ("other", "Other"),
                ],
                default="",
                max_length=50,
                verbose_name="Marital Status",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone_type",
            field=models.CharField(
                blank=True,
                choices=[("home", "Home"), ("office", "Office"), ("mobile", "Mobile"), ("other", "Other")],
                default="",
                max_length=10,
                verbose_name="Phone Type",
            ),
        ),
    ]
