# Generated by Django 4.2.9 on 2024-02-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_alter_lead_contact_type_alter_lead_marital_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="user",
        ),
    ]
