# Generated by Django 4.2.9 on 2024-02-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_remove_lead_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
    ]
