# Generated by Django 4.2.9 on 2024-02-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_alter_lead_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=100, unique=True, verbose_name="Email"),
        ),
    ]
