version: '3'

volumes:
  staging_postgres_data: {}
  staging_postgres_data_backups: {}
  staging_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/staging/django/Dockerfile

    image: gojjo_realty_staging_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.staging/.django
      - ./.envs/.staging/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/staging/postgres/Dockerfile
    image: gojjo_realty_staging_postgres
    volumes:
      - staging_postgres_data:/var/lib/postgresql/data
      - staging_postgres_data_backups:/backups
    env_file:
      - ./.envs/.staging/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/staging/traefik/Dockerfile
    image: gojjo_realty_staging_traefik
    depends_on:
      - django
    volumes:
      - staging_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:442:443'
      - '0.0.0.0:5550:5555'

  redis:
    image: docker.io/redis:6

  celeryworker:
    <<: *django
    image: gojjo_realty_staging_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: gojjo_realty_staging_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: gojjo_realty_staging_flower
    command: /start-flower
