# Generated by Django 4.2.9 on 2024-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calltoaction",
            name="button_url",
        ),
        migrations.AlterField(
            model_name="calltoaction",
            name="button_text",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="button text"),
        ),
        migrations.AlterField(
            model_name="calltoaction",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="subtitle"),
        ),
    ]
