# Generated by Django 4.2.9 on 2024-02-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_remove_calltoaction_button_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="header_text",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="header text"),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="subtitle"),
        ),
    ]
