# Generated by Django 4.2.9 on 2024-02-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_links_link_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinfo",
            name="site_description",
            field=models.TextField(blank=True, null=True, verbose_name="site description"),
        ),
    ]
