# Generated by Django 4.2.9 on 2024-02-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_aboutpage_header_text_aboutpage_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="header_text",
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name="header text"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="subtitle",
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name="subtitle"),
        ),
    ]
