# Generated by Django 4.2.9 on 2024-02-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_aboutpage_header_text_alter_aboutpage_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="client_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="testimonials/uploads/", verbose_name="client image"
            ),
        ),
    ]
