# Generated by Django 4.2.9 on 2024-02-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_service_page_header_service_page_subheader"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified_date", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("special", "Special"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="type",
                    ),
                ),
                ("page_header", models.CharField(blank=True, max_length=255, null=True, verbose_name=" page header")),
                (
                    "page_subheader",
                    models.TextField(blank=True, max_length=500, null=True, verbose_name="page subheader"),
                ),
            ],
            options={
                "verbose_name": "services page",
                "verbose_name_plural": "services pages",
                "ordering": ["-created_date"],
            },
        ),
        migrations.RemoveField(
            model_name="service",
            name="page_header",
        ),
        migrations.RemoveField(
            model_name="service",
            name="page_subheader",
        ),
    ]
