# Generated by Django 4.2.9 on 2024-02-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_servicespage_remove_service_page_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="service_icon",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="service icon"),
        ),
        migrations.AlterField(
            model_name="servicespage",
            name="page_header",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="page header"),
        ),
    ]
