# Generated by Django 4.2.9 on 2024-02-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_service_service_icon_alter_servicespage_page_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_video_url",
            field=models.URLField(blank=True, null=True, verbose_name="hero video url"),
        ),
    ]
