# Generated by Django 4.2.9 on 2024-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_alter_contactmessage_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="contact_cta",
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name="contact cta"),
        ),
    ]
