# Generated by Django 4.2.9 on 2024-02-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("property_name", models.CharField(max_length=255, verbose_name="Property Name")),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("single_family", "Single Family"),
                            ("condo", "Condo"),
                            ("townhome", "Townhome"),
                            ("multifamily", "Multifamily"),
                            ("apartment", "Apartment"),
                            ("commercial", "Commercial"),
                            ("land", "Land"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "property_address",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Property Address"),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True, verbose_name="City")),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("DC", "District Of Columbia"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                            ("AS", "American Samoa"),
                            ("GU", "Guam"),
                            ("MP", "Northern Mariana Islands"),
                            ("PR", "Puerto Rico"),
                            ("UM", "United States Minor Outlying Islands"),
                            ("VI", "Virgin Islands"),
                            ("AA", "Armed Forces Americas"),
                            ("AP", "Armed Forces Pacific"),
                            ("AE", "Armed Forces Others"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                ("zip_code", models.CharField(blank=True, max_length=255, null=True, verbose_name="Zip Code")),
                ("property_description", models.TextField(blank=True, null=True, verbose_name="Property Description")),
                (
                    "property_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_images", verbose_name="Property Image"
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Sale Price"
                    ),
                ),
                (
                    "rental_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Rental Income"
                    ),
                ),
                (
                    "operating_expenses",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Operating Expense"
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Financing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Purchase Price"),
                ),
                (
                    "down_payment",
                    models.DecimalField(decimal_places=2, default=20, max_digits=10, verbose_name="Down Payment"),
                ),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=2, default=6.5, max_digits=10, verbose_name="Interest Rate"),
                ),
                ("loan_term", models.IntegerField(default=30, verbose_name="Loan Term")),
                (
                    "loan_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Loan Amount"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financing",
                        to="calculators.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financing",
                "verbose_name_plural": "Financings",
                "ordering": ["-created_at"],
            },
        ),
    ]
