# Generated by Django 4.2.9 on 2024-02-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_remove_post_user_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
