# Generated by Django 4.2.9 on 2024-02-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                blank=True,
                choices=[("home", "Home"), ("office", "Office"), ("other", "Other")],
                max_length=255,
                verbose_name="Address Type",
            ),
        ),
    ]
