# Generated by Django 4.2.9 on 2024-02-12 21:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_address_address_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="alternate_email",
            field=models.EmailField(blank=True, max_length=255, verbose_name="Alternate Email"),
        ),
        migrations.AddField(
            model_name="agent",
            name="alternate_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Alternate Phone Number"
            ),
        ),
    ]
