# Generated by Django 4.2.9 on 2024-02-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agentpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Publish"),
        ),
    ]
