# Generated by Django 4.2.9 on 2024-02-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_alter_agent_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="agent_short_bio",
            field=models.TextField(blank=True, max_length=255, verbose_name="Short Bio"),
        ),
    ]
