# Generated by Django 4.2.9 on 2024-02-09 03:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agent_agent_short_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="practice_areas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None
            ),
        ),
    ]
