# Generated by Django 4.2.9 on 2024-02-09 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_agent_practice_areas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="focus_areas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, max_length=255), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="practice_areas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, max_length=255), blank=True, null=True, size=None
            ),
        ),
    ]
