# Generated by Django 4.2.9 on 2024-02-04 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0003_alter_agent_is_published"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("first_name", models.CharField(max_length=100, verbose_name="First Name")),
                ("last_name", models.CharField(max_length=100, verbose_name="Last Name")),
                ("email", models.EmailField(max_length=100, unique=True, verbose_name="Email")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Phone Number"
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        choices=[("home", "Home"), ("office", "Office"), ("mobile", "Mobile"), ("other", "Other")],
                        default="mobile",
                        max_length=10,
                        verbose_name="Phone Type",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[("client", "Client"), ("vendor", "Vendor"), ("other", "Other")],
                        default="other",
                        max_length=10,
                        verbose_name="Relationship",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-Binary"),
                            ("refuse_id", "Refuse to Identify"),
                            ("other", "Other"),
                        ],
                        verbose_name="Gender",
                    ),
                ),
                ("birthdate", models.DateField(blank=True, null=True, verbose_name="Birthdate")),
                (
                    "pronoun",
                    models.CharField(
                        blank=True,
                        choices=[("he", "He/Him"), ("she", "She/Her"), ("they", "They/Them"), ("other", "Other")],
                        verbose_name="Pronoun",
                    ),
                ),
                ("can_text", models.BooleanField(default=True, verbose_name="Can Text")),
                (
                    "contact_type",
                    models.CharField(
                        choices=[("client", "Client"), ("vendor", "Vendor"), ("other", "Other")],
                        default="client",
                        max_length=10,
                        verbose_name="Contact Type",
                    ),
                ),
                ("can_email", models.BooleanField(default=True, verbose_name="Can Email")),
                ("can_snail_mail", models.BooleanField(default=False, verbose_name="Can Snail Mail")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Realtionship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("first_name", models.CharField(max_length=100, verbose_name="First Name")),
                ("last_name", models.CharField(max_length=100, verbose_name="Last Name")),
                ("email", models.EmailField(max_length=100, unique=True, verbose_name="Email")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Phone Number"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="Relationship",
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True, verbose_name="Birthday")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-Binary"),
                            ("refuse_id", "Refuse to Identify"),
                            ("other", "Other"),
                        ],
                        verbose_name="Gender",
                    ),
                ),
                (
                    "pronoun",
                    models.CharField(
                        blank=True,
                        choices=[("he", "He/Him"), ("she", "She/Her"), ("they", "They/Them"), ("other", "Other")],
                        verbose_name="Pronoun",
                    ),
                ),
                ("is_emergency_contact", models.BooleanField(default=False, verbose_name="Is Emergency Contact")),
                ("is_primary_contact", models.BooleanField(default=False, verbose_name="Is Primary Contact")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="contacts.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "related_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_contacts",
                        to="contacts.contact",
                        verbose_name="Related Contact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("postal_code", models.CharField(max_length=10, verbose_name="Postal Code")),
                (
                    "address_type",
                    models.CharField(
                        choices=[("home", "Home"), ("office", "Office"), ("other", "Other")],
                        default="home",
                        max_length=20,
                        verbose_name="Address Type",
                    ),
                ),
                ("current_address", models.BooleanField(default=True, verbose_name="Current Address")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_address",
                        to="contacts.contact",
                        verbose_name="Contact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactAdditionalInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                            ("cohabit", "Co-Habitating"),
                            ("other", "Other"),
                        ],
                        default="single",
                        max_length=50,
                        verbose_name="Marital Status",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self-Employed"),
                            ("unemployed", "Unemployed"),
                            ("retired", "Retired"),
                            ("student", "Student"),
                            ("other", "Other"),
                        ],
                        default="employed",
                        max_length=50,
                        verbose_name="Employment Status",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("college", "College"),
                            ("university", "University"),
                            ("graduate", "Graduate"),
                            ("other", "Other"),
                        ],
                        default="high_school",
                        max_length=50,
                        verbose_name="Education Level",
                    ),
                ),
                (
                    "income_level",
                    models.CharField(
                        choices=[("low", "Low"), ("middle", "Middle"), ("high", "High"), ("other", "Other")],
                        default="middle",
                        max_length=50,
                        verbose_name="Income Level",
                    ),
                ),
                (
                    "household_income_level",
                    models.CharField(
                        choices=[("low", "Low"), ("middle", "Middle"), ("high", "High"), ("other", "Other")],
                        default="middle",
                        max_length=100,
                        verbose_name="Household Income Level",
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("text", "Text"),
                            ("snail_mail", "Snail Mail"),
                            ("other", "Other"),
                        ],
                        default="email",
                        max_length=50,
                        verbose_name="Preferred Contact Method",
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_info",
                        to="contacts.contact",
                        verbose_name="Contact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="addresses",
            field=models.ManyToManyField(
                related_name="contact_addresses", to="contacts.contactaddress", verbose_name="Addresses"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="agents.agent",
                verbose_name="Agent",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Contact User",
            ),
        ),
    ]
