# Generated by Django 4.2.9 on 2024-02-05 16:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relationship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("first_name", models.CharField(max_length=100, verbose_name="First Name")),
                ("last_name", models.CharField(max_length=100, verbose_name="Last Name")),
                ("email", models.EmailField(max_length=100, unique=True, verbose_name="Email")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Phone Number"
                    ),
                ),
                (
                    "phone_number_type",
                    models.CharField(
                        choices=[("home", "Home"), ("office", "Office"), ("mobile", "Mobile"), ("other", "Other")],
                        default="mobile",
                        verbose_name="Phone Number Type",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="Relationship",
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True, verbose_name="Birthday")),
                ("anniversary", models.DateField(blank=True, null=True, verbose_name="Anniversary")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-Binary"),
                            ("refuse_id", "Refuse to Identify"),
                            ("other", "Other"),
                        ],
                        verbose_name="Gender",
                    ),
                ),
                (
                    "pronoun",
                    models.CharField(
                        blank=True,
                        choices=[("he", "He/Him"), ("she", "She/Her"), ("they", "They/Them"), ("other", "Other")],
                        verbose_name="Pronoun",
                    ),
                ),
                ("is_emergency_contact", models.BooleanField(default=False, verbose_name="Is Emergency Contact")),
                ("is_primary_contact", models.BooleanField(default=False, verbose_name="Is Primary Contact")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="contact",
            name="relationship",
        ),
        migrations.RemoveField(
            model_name="contactadditionalinfo",
            name="marital_status",
        ),
        migrations.RemoveField(
            model_name="contactadditionalinfo",
            name="preferred_contact_method",
        ),
        migrations.AddField(
            model_name="contact",
            name="additional_info",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additonal_info",
                to="contacts.contactadditionalinfo",
                verbose_name="Additional Info",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                    ("cohabit", "Co-Habitating"),
                    ("other", "Other"),
                ],
                default="single",
                max_length=50,
                verbose_name="Marital Status",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("text", "Text"),
                    ("snail_mail", "Snail Mail"),
                    ("other", "Other"),
                ],
                default="email",
                max_length=20,
                verbose_name="Preferred Contact Method",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="addresses",
            field=models.ManyToManyField(
                related_name="addresses", to="contacts.contactaddress", verbose_name="Addresses"
            ),
        ),
        migrations.AlterField(
            model_name="contactadditionalinfo",
            name="contact",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_additional_info",
                to="contacts.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.DeleteModel(
            name="Realtionship",
        ),
        migrations.AddField(
            model_name="relationship",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_relationships",
                to="contacts.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="relationships",
            field=models.ManyToManyField(
                related_name="relationships", to="contacts.relationship", verbose_name="Relationships"
            ),
        ),
    ]
