# Generated by Django 4.2.9 on 2024-02-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agent_use_alt_email"),
        ("landingpages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255, verbose_name="First Name")),
                ("last_name", models.CharField(max_length=255, verbose_name="Last Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=255, verbose_name="Phone")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "attending",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("maybe", "Maybe"), ("other", "Other")],
                        max_length=255,
                        verbose_name="Attending",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("city", models.CharField(max_length=255, verbose_name="City")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("DC", "District Of Columbia"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                            ("AS", "American Samoa"),
                            ("GU", "Guam"),
                            ("MP", "Northern Mariana Islands"),
                            ("PR", "Puerto Rico"),
                            ("UM", "United States Minor Outlying Islands"),
                            ("VI", "Virgin Islands"),
                            ("AA", "Armed Forces Americas"),
                            ("AP", "Armed Forces Pacific"),
                            ("AE", "Armed Forces Others"),
                        ],
                        max_length=255,
                        verbose_name="State",
                    ),
                ),
                ("zip_code", models.CharField(max_length=255, verbose_name="Zip Code")),
                ("phone", models.CharField(max_length=255, verbose_name="Phone")),
                ("website", models.URLField(verbose_name="Website")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
            },
        ),
        migrations.AddField(
            model_name="landingpage",
            name="agents",
            field=models.ManyToManyField(
                blank=True, related_name="landing_pages", to="agents.agent", verbose_name="Agents"
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="End Time"),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="landingpages", verbose_name="Featured Image"),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Start Time"),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("cancelled", "Cancelled"),
                    ("other", "Other"),
                ],
                default="draft",
                max_length=255,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open_house", "Open House"),
                    ("workshop", "Workshop"),
                    ("trade_show", "Trade Show"),
                    ("showing", "Showing"),
                    ("meeting", "Meeting"),
                    ("other", "Other"),
                ],
                max_length=255,
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, related_name="landing_pages", to="landingpages.contact", verbose_name="Contacts"
            ),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_pages",
                to="landingpages.venue",
                verbose_name="Venue",
            ),
        ),
    ]
