# Generated by Django 4.2.9 on 2024-02-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_agent_use_alt_email"),
        ("landingpages", "0002_contact_venue_landingpage_agents_landingpage_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpage",
            name="agents",
        ),
        migrations.AddField(
            model_name="landingpage",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_pages",
                to="agents.agent",
                verbose_name="Organizer",
            ),
        ),
    ]
