# Generated by Django 4.2.9 on 2024-02-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0004_contact_landing_page_venue_landing_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Ateendee", "verbose_name_plural": "Atendees"},
        ),
        migrations.AlterModelOptions(
            name="landingpage",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
        migrations.AddField(
            model_name="landingpage",
            name="event_link",
            field=models.URLField(blank=True, null=True, verbose_name="Event Link"),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="online_event",
            field=models.BooleanField(default=False, verbose_name="Online Event"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="attending",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("maybe", "Maybe"), ("other", "Other")],
                default="yes",
                max_length=255,
                verbose_name="Attending",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="landing_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landingpage_venues",
                to="landingpages.landingpage",
                verbose_name="Event",
            ),
        ),
    ]
