# Generated by Django 4.2.9 on 2024-02-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0005_alter_contact_options_alter_landingpage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventFAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                (
                    "landing_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_faqs",
                        to="landingpages.landingpage",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event FAQ",
                "verbose_name_plural": "Event FAQs",
            },
        ),
    ]
