# Generated by Django 4.2.9 on 2024-02-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0006_eventfaq"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="faqs",
            field=models.ManyToManyField(
                blank=True, related_name="landing_pages", to="landingpages.eventfaq", verbose_name="FAQs"
            ),
        ),
    ]
