# Generated by Django 4.2.9 on 2024-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpages", "0007_landingpage_faqs"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfaq",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
    ]
